version: "3.7"
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: PLEASE_INPUT_PASSWORD
      MYSQL_DATABASE: PLEASE_INPUT_DATABASE_NAME
    restart: on-failure
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: USE_YOUR_IP

  server:
    build: .
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      DB_URL: mysql://root:MYSQL_ROOT_PASSWORD@DB_IP_ADDRESS/sample
    entrypoint: "npm run dev"
    networks:
      default:
        ipv4_address: USE_YOUR_IP

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: USE_YOUR_IP
